// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package OOADAssign01;

/************************************************************/
/**
 * 
 */
public class Doctor extends HospitalWorker {
	/**
	 * 
	 */
	public void VisitPatients() {
	}
};
