// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package OOADAssign01;

/************************************************************/
/**
 * 
 */
public class EmergencyDepartment extends Departments {
};
