// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package OOADAssign01;

/************************************************************/
/**
 * 
 */
public class HospitalWorker extends Person {
	/**
	 * 
	 */
	private String ID;
};
