// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package OOADAssign01;

/************************************************************/
/**
 * 
 */
public class Patient extends Person {
	/**
	 * 
	 */
	public void BooksAppointment() {
	}

	/**
	 * 
	 */
	public void PurchaseMedicines() {
	}
};
